### ISSUE TITLE
Add ability to specify pattern using KP's built-in placeholders

### ISSUE THREAD

**Issue by numericOverflow** [ihanson/KeePass-Rule-Builder#1]
The ability to "Add Character Set" is nice, but I think it would be even better if it were possible to define placeholder patterns using the same syntax as the built-in password generator profiles.

- https://keepass.info/help/base/pwgenerator.html#pattern

That way you could have excellent compatibility with existing functionality, and could move patterns out of profiles and into the rules attached to entries themselves. 

Here's a quick mock-up of what I'm suggesting:
![2019-08-07_154656](https://user-images.githubusercontent.com/3429424/62657286-c288fa80-b92b-11e9-8dfd-2d4146666754.jpg)

Keep the ability to define simple characters, but also add the ability to do custom placeholder patterns.

**Comment by ihanson** [comment]
Do you have a specific case in mind where this would be helpful? I think the predefined character classes that I have, along with custom character sets, should be enough for just about any password rule. I haven’t seen any services whose password rules would be made easier if KeePass’s placeholder patterns were available here in addition to what the plugin already provides.

The goal of this user interface is not to replace KeePass’s profiles entirely, but to make it so that in most cases users don’t have to think like a programmer in order to use the password generator. Allowing KeePass’s placeholder syntax does not advance this goal.
