### ISSUE TITLE
RuleBuilder 3.3 not compatible with KeePass 2.51.1?

### ISSUE THREAD

**Issue by awesomecogs** [ihanson/KeePass-Rule-Builder#13]
I'm getting the following message from KeePass upon startup...

![image](https://user-images.githubusercontent.com/44172583/173097268-eb16a909-9a88-4f78-aec0-b0afbb58f01f.png)

I'm running KeePass 2.51.1, released on 2022-05-09.  I'm used to .plgx files so wasn't completely sure where to put the .dll, but I've received the same message with the .dll located in both the root KeePass folder and Plugins folder.

Any ideas?  Many thanks!!

**Comment by awesomecogs** [comment]
I noticed that v3.4 was released a few days ago.  I was hoping it would resolve my issue but I'm still getting the same message...

![image](https://user-images.githubusercontent.com/44172583/185418759-250721a0-2695-4f6a-a661-fef331e6606d.png)

Am I the only one using this plugin thus the only one having problems, or is this an uncommon error that's stumped everyone?

Thanks much!

**Comment by ihanson** [comment]
I’m not seeing that error, so it seems like an issue with your installation. You should just need to copy [RuleBuilder.dll](https://github.com/ihanson/KeePass-Rule-Builder/releases/tag/v3.4) into the `C:\Program Files\KeePass Password Safe 2\Plugins` folder.

Can you post the contents of `C:\Program Files\KeePass Password Safe 2\KeePass.exe.config`? With issue #4, that turned out to be the culprit.

Maybe try uninstalling and reinstalling KeePass and seeing if that helps.

**Comment by ihanson** [comment]
Actually, I just figured it out: **The DLL file name needs to exactly match `RuleBuilder.dll`.** Yours is named `RuleBuilder-3.4.dll`, which causes that crash. KeePass uses the DLL name to guess the name of the plugin type.

**Comment by awesomecogs** [comment]
You are absolutely right, Ira.  I'm used to the plugins I already use working fine with their name changed to include the version number that it didn't even cross my mind for yours (or the other one or two plugins having problems).  Many thanks for helping me with the "duh!" moment!  Now I'm off to get RuleBuilder working in my database.  Thanks for all your hard work with the plugin and putting up with users like me.  😉
