### ISSUE TITLE
Add password quality meter display?

### ISSUE THREAD

**Issue by numericOverflow** [ihanson/KeePass-Rule-Builder#2]
Is it possible to include a quality meter on the change password dialog box?  It wouldn't *have* to be a bar meter, even just the quality bits number would be helpful to know.

I've really fallen in love with your extension.  That said, I find myself guessing at the quality value when using the rule-builder dialog, whereas the built-in interface shows the quality.  It might be nice to see both the old & new quality bits, as long as your displaying one, having both for reference might be even better.

Here's a quick mockup of what I was thinking:
![kp_quality_meter_mockup](https://user-images.githubusercontent.com/3429424/77860862-2e7be400-71d7-11ea-9e61-73ddf6637f8d.jpg)

Thoughts?

**Comment by ihanson** [comment]
My feeling on this is that a password strength meter would be counterproductive to the purpose of a random password generator. Password strength meters may be useful if you’re creating a password non-randomly, to ensure that you’re including a good mix of character types, but a randomly generated password is always going to be very strong. The set of possible passwords is as large as it can get, and each password in that set is approximately equally likely. The only possible attack against a properly hashed random password is a brute force attack that searches the entire space of valid passwords of the configured length.

A strength meter may actually cause users to *reduce* the strength of their passwords, because if they observe that the password is measured to be weaker than they expect, they will generate another password in an attempt to increase the measured strength. That actually slightly reduces the true strength because it reduces the effective size of the password space to only those passwords whose measured strength (according to the strength meter’s algorithm) is above some arbitrary threshold.

**Comment by ihanson** [comment]
The calculated password strength is now shown in the rule editor in [Version 3.0](https://github.com/ihanson/KeePass-Rule-Builder/releases/tag/v3.0).
